---
- name: "PRELIM | Find all sudoers files."
  command: "find /etc/sudoers /etc/sudoers.d/ -type f ! -name '*~' ! -name '*.*'"
  changed_when: no
  failed_when: no
  register: rhel7stig_sudoers_files
  when:
      - rhel_07_010340 or
        rhel_07_010350
  tags:
      - cat2
      - medium
      - RHEL-07-010340
      - RHEL-07-010350

- name: "PRELIM | RHEL-07-010480 RHEL-07-010490 RHEL-07-021350 | Install grub2-tools."
  yum:
      name: grub2-tools
  when:
      - rhel_07_010480 or
        rhel_07_010490 or
        rhel_07_021350
  tags:
      - cat1
      - high
      - RHEL-07-010480
      - RHEL-07-010490
      - RHEL-07-021350

- name: "PRELIM | RHEL-07-010480 RHEL-07-010490 RHEL-07-021350 RHEL-07-021700 | Check whether machine is UEFI-based"
  stat:
      path: /sys/firmware/efi
  register: rhel_07_sys_firmware_efi
  when:
      - rhel_07_010480 or
        rhel_07_010490 or
        rhel_07_021350 or
        rhel_07_021700
  tags:
      - cat1
      - high
      - cat2
      - medium
      - RHEL-07-010480
      - RHEL-07-010490
      - RHEL-07-021350
      - RHEL-07-021700

- name: "PRELIM | Gather mount information"
  setup:
      gather_subset: hardware,!all,!min
      filter: ansible_mounts
  when:
      - ansible_mounts is not defined
  tags:
      - always

- name: "PRELIM | RHEL-07-020620 RHEL-07-020630 RHEL-07-020640 RHEL-07-020650 RHEL-07-020660 RHEL-07-020690 | Parse /etc/passwd"
  include_tasks: parse_etc_passwd.yml
  vars:
      rhel7stig_passwd_tasks: "RHEL-07-020620 RHEL-07-020630 RHEL-07-020640 RHEL-07-020650 RHEL-07-020660 RHEL-07-020690"
  when:
      - rhel_07_020620 or
        rhel_07_020630 or
        rhel_07_020640 or
        rhel_07_020650 or
        rhel_07_020660 or
        rhel_07_020670 or
        rhel_07_020690 or
        rhel_07_020700 or
        false
  tags:
      - cat2
      - medium
      - RHEL-07-020620
      - RHEL-07-020630
      - RHEL-07-020640
      - RHEL-07-020650
      - RHEL-07-020660
      - RHEL-07-020670
      - RHEL-07-020690
      - RHEL-07-020700

- name: "PRELIM | RHEL-07-021100 RHEL-07-031000 RHEL-07-031010 | Ensure rsyslog is installed when required."
  yum:
      name: rsyslog
  when:
      - rhel_07_021100 or
        rhel_07_031000 or
        rhel_07_031010
  tags:
      - cat2
      - medium
      - RHEL-07-021100
      - RHEL-07-031000
      - RHEL-07-031010

- name: "PRELIM | RHEL-07-021350 | Check if /boot or /boot/efi reside on separate partitions"
  shell: df --output=target /boot/efi | tail -n 1
  changed_when: no
  check_mode: no
  register: rhel_07_boot_part
  when:
      - rhel_07_021350
  tags:
      - cat1
      - high
      - RHEL-07-021350

- name: "PRELIM | RHEL-07-030330 | Determine audit log partition."
  block:
      - name: "PRELIM | RHEL-07-030330 | Find audit.log location"
        command: grep -oP '^log_file\s*=\s*\K.*?(?=\s*$)' /etc/audit/auditd.conf
        changed_when: no
        check_mode: no
        register: rhel_07_audit_log_file

      - name: "PRELIM | RHEL-07-030330 | Find partition holding audit.log"
        shell: df --output=target {{ rhel_07_audit_log_file.stdout }} | tail -n 1
        changed_when: no
        check_mode: no
        register: rhel_07_audit_part
  when:
      - rhel_07_030330
  tags:
      - cat2
      - medium
      - RHEL-07-030330

- name: "PRELIM | RHEL-07-030300 RHEL-07-030310 RHEL-07-030320 RHEL-07-030321 | Install audit remote plugin."
  yum:
      name: audispd-plugins
  when:
      - rhel_07_030300 or
        rhel_07_030310 or
        rhel_07_030320 or
        rhel_07_030321
  tags:
      - cat2
      - medium
      - RHEL-07-030300
      - RHEL-07-030310
      - RHEL-07-030320
      - RHEL-07-030321

- name: "PRELIM | RHEL-07-040410 | The SSH public host key files must have mode 0644 or less permissive."
  find:
      paths: /etc/ssh
      recurse: yes
      file_type: file
      patterns: 'ssh_host*_key.pub'
      hidden: true
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_040410_audit
  when: rhel_07_040410
  tags:
      - cat2
      - medium
      - RHEL-07-040410
      - ssh

- name: "PRELIM | RHEL-07-040420 | The SSH private host key files must have mode 0600 or less permissive."
  find:
      paths: /etc/ssh
      recurse: yes
      file_type: file
      patterns: 'ssh_host*_key'
      hidden: true
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_040420_audit
  when: rhel_07_040420
  tags:
      - cat2
      - medium
      - RHEL-07-040420
      - ssh

- name: "PRELIM | RHEL-07-020030 RHEL-07-020040 RHEL-07-021600 RHEL-07-021610 RHEL-07-021620 | Install and initialize AIDE"
  block:
      - name: "PRELIM | RHEL-07-020030 RHEL-07-020040 RHEL-07-021600 RHEL-07-021610 RHEL-07-021620 | Install AIDE"
        yum:
            name: aide
            state: present
        notify: "{{ rhel7stig_aide_handler }}"

      - name: "PRELIM | RHEL-07-020030 RHEL-07-020040 RHEL-07-021600 RHEL-07-021610 RHEL-07-021620 | Check for existing AIDE database"
        stat:
            path: "{{ rhel7stig_aide_db_file }}"
        register: rhel7stig_aide_db_status
        check_mode: no
        changed_when: not rhel7stig_aide_db_status.stat.exists
        notify: "{{ rhel7stig_aide_handler }}"
  when:
      - rhel_07_020030 or
        rhel_07_020040 or
        rhel_07_021600 or
        rhel_07_021610 or
        rhel_07_021620
  tags:
      - cat2
      - medium
      - patch
      - aide
      - RHEL-07-020030
      - RHEL-07-020040
      - RHEL-07-021600
      - RHEL-07-021610
      - RHEL-07-021620
